[package]
name = "superbible"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
glfw = "0.28.0"
gl = "0.12.0"

[[bin]]
name = "solid-red"
path = "src/00_solidred.rs"

[[bin]]
name = "colors"
path = "src/01_colors.rs"

[[bin]]
name = "point"
path = "src/02_point.rs"

[[bin]]
name = "triangle"
path = "src/03_triangle.rs"