[package]
name = "superbible"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
gl = "0.14.0"
glutin = "0.26.0"
nalgebra-glm = "0.12.0"
nom = "5.0.1"
rand = "0.8.3"

[lib]
name = "support"
path = "src/support/lib.rs"
